server:
  port: 0

spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
    data:
      mongodb:
        database: test
        port: 27017
  zipkin:
    baseUrl: http://localhost:9411/
    enable: true

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5672

queue:
  pelicula:
    name: colaPelicula
  serie:
    name: colaSerie

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enable: true
  service-url:
    default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true