server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: movie-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3370/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate:
      ddl-auto: update

  zipkin:
    baseUrl: http://localhost:9411/
    enable: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  pelicula:
    name: pelicula




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enable: true
  service-url:
    default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enable: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: "movie-service"
    description: "Microservicio de película -> parcial Especializacion Backend I"
