server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enable: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

